apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: NodePort
  selector:
    app: hello-kubernetes
  ports:
  - protocol: TCP
    port: 80  # The port that will be exposed externally
    targetPort: 8080  # The container port in the deployment
    nodePort: 32000  # You can specify a NodePort (range 30000–32767) or let Kubernetes assign one



